computerteam9/MEETEAM

- README.md
- android/build.gradle
- lib/main.dart
- lib/memberApplication_Page.dart
- lib/write_Page.dart
> 추가:3-글-페이지_전체

- lib/main_page.dart
> 6 홈 페이지 - 추천 리스트 구현

- lib/app_bar_goback.dart
- lib/main.dart
- lib/user_check.dart
**구현한 내용**
- 프로필 이미지, 간단정보 표시 화면
- APPBAR 뒤로가기
> 2 신청자 확정 페이지 - 프로필 표시 화면 구현

- lib/color.dart
- lib/explorer_page.dart
- lib/main.dart
- lib/main_page.dart
* 검색 입력란, 버튼 생성
* Toggle 가능한 태그 버튼 생성
> 5 탐색 페이지 - 검색 창 UI 구현

- lib/ApplicationReadPage.dart
- lib/ApplicationWritePage.dart
- lib/MainPage.dart
- lib/ProjectReadPage.dart
- lib/ProjectWritePage.dart
- lib/main.dart
ProjectWirtePage.dart 내부의 class 네임 변경
WritePage -> ProjectWritePage
_WritePageState -> _ProjectWritePageState
ApplicationPage.dart -> ApplicationWritePage.dart
ApplicationWritePage -> ApplicationWritePage
_ApplicationWritePageState -> _ApplicationWritePageState
+) MainPage내부의 WritePage() -> ProjectWritePage()
> 17 프로젝트 상세화면 페이지

- lib/MainPage.dart
- lib/ProjectListPage.dart
- lib/color.dart
- 나의 프로젝트 화면 구현
- +버튼 연동
- CustomColor 코드 변경
> 16 나의 프로젝트 화면 구현

- lib/UserCheckPage.dart
- lib/UserListPage.dart
- lib/main.dart
신청자 목록 화면 제작
신청자 목록 화면이랑 신청자 개별 확정 화면이랑 클릭 시 서로 이동할 수 있도록 연결해놓음
> 14 신청자 내역 화면 만들기

- lib/Appbar/EditAppbar.dart
- lib/ProfileWritePage.dart
- lib/SignupPage.dart
회원 가입 시 조건 작성 순서 상관 없이 가입 버튼 가능 
스크롤 구현해서 overflow 안 생기게 함
Signup->profilewritepage->main
profilepage->profilewritepage->profilepage 페이지 전환 설정
> 24 5월 1주차 심여민

- lib/MainPage.dart
- lib/ProjectBox.dart
- lib/ProjectListPage.dart
- lib/main.dart
- 플로팅 글쓰기 버튼
- 프로젝트 내역 스크롤
- ProjectBox 분리
- 내 프로젝트 -> 팀장 시점 글 연동
- Debug 배너 삭제
- MainPage, ProjectListPage ProjectBox 적용
> 25 5월 1주차 박정현

- ios/Runner/Info.plist
- lib/ApplicationCheckPage.dart
- lib/ApplicationFinishedPage.dart
- lib/ProjectWriteFinishedPage.dart
- lib/ProjectWritePage.dart
- lib/main.dart
글(팀원 지원 후) 페이지 완료
등록완료 페이지 완료
지원완료 페이지 완료
> 26-5월-1주차-손예진

- lib/SelfCheckPage.dart
- lib/UserListPage.dart
- lib/main.dart
화면 만들기 완료
팀장 시점 화면 연결하기 완료
팀원 시점 화면 연결하기 미완료(예진이가 이번에 만드는 중이라 회의 이후에 연결할 예정)
스크롤 구현 완
> 28 5월 1주차 김은수

- lib/Api/user_api.dart
- lib/main.dart
* UserApi 클래스 내 verifyUser 함수 구현
* 인자 : String email, String password
* 반환값 Future<String>
* 로그인 성공 시 : 해당 유저의 ID
* 로그인 실패 시 : ""(빈 문자열)
* 사용 예시
```dart
UserApi.verifyUser('em', 'password').then((value) {
// 여기서 value가 유저의 ID
});
```
> 추가 : verifyUser 함수 구현

- lib/Api/user_api.dart
- lib/Model/user.dart
- lib/main.dart
1. 이메일 중복 검사
2. 닉네임 중복 검사
* 각각의 경우 addUser함수가 Exception을 발생시킨다, 앱 단에서 예외처리 필요
> 추가 : addUser함수

- lib/Api/db.dart
- lib/Api/project_api.dart
- lib/Api/user_api.dart
- lib/Model/project.dart
- lib/main.dart
- pubspec.yaml
* project 모델 구현
* addProject 함수 구현
* db 인스턴스 분리
> 67 project model 구현

- lib/Api/session.dart
- lib/main.dart
* 로그인 세션 클래스 구현
* 사용법
``` dart
import 'package:meetteam/Api/session.dart';
...
UserApi.verifyUser("abc@abc.com", "passss").then((id) {
Session.set(id); // Session에 현재 로그인한 유저의 id 저장
print(Session.get()); // Session에 저장된 유저 id 가져오기
}
```
> 추가 : session class 구현

- lib/Appbar/edit_appbar.dart
- lib/Appbar/logo_appbar.dart
- lib/Appbar/main_appbar.dart
- lib/Appbar/normal_appbar.dart
- lib/Appbar/write_appbar.dart
- lib/Project/project_write_page.dart
-  프로젝트 날짜 형식 제한 
- 프로젝트 제목, 내용 힌트 텍스트 추가
- 프로젝트 마감 날짜 추가, 형식 제한
- 중앙 로고 클릭시 홈 이동
*클릭시 화면 클릭 해제시 색 없음
> 57 5월 4주차 박정현

- lib/Api/project_api.dart
- lib/Api/user_api.dart
- lib/Model/project.dart
- lib/Model/user.dart
* resolve #78 
```dart
// 0번째 : 자신이 리더인 프로젝트의 id, 1번째 : 자신이 신청한/멤버인 프로젝트의 id
List<List<String>> _project = <List<String>>[];
```
```dart
// 리더의 user ID
String _leaderId;
```
* 각 Api 클래스의 함수 호출할 때 바뀐 내용 적용할 것
> 78 model 수정

- lib/Project/project_write_page.dart
DateTime 수정
Expanded , Wrap 수정 필요
> 프로젝트 생성 DateTime 수정

- lib/Api/user_api.dart
- lib/Model/user.dart
- lib/Project/project_read_page.dart
- lib/Project/project_write_page.dart
> 수정 : User model > project : Map<String, List>

- lib/main.dart
- lib/main_page.dart
* 프로젝트가 한개라도 있을 때
* 프로젝트가 한개도 없을 때
> 117 내 프로젝트 구현

- lib/Project/project_write_page.dart
- lib/main_page.dart
> 123 d day 해결 완

- lib/Profile/profile_write_page.dart
- lib/Project/self_check_page.dart
- lib/Project/user_check_page.dart
- lib/application_write_page.dart
* 회원가입 직후 닉네임 
* 수정 후 재실행, 로그인 직후 프로필 수정 페이지
> 128 user 값 읽고 초기화

- lib/Project/project_list_page.dart
- lib/Project/project_read_page.dart
- lib/Widgets/project_box.dart
project list page  
leader / member project 표시
> 118 내 프로젝트 리스트 구현

- lib/Project/project_read_page.dart
- lib/explorer_page.dart
커밋 내용 실수
1, 모집 인원 멤버 2번 표시 안되는 오류 수정 
2. 오버플로우 마진 수정
3. 검색 페이지 날짜 오류 수정
> 136 project read 페이지 멤버 2번 표시 오류
